import { Sriracha } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from "next/link";

const sriracha = Sriracha({ weight: ['400', '400'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sriracha.className}>
        {children}
      </body>
    </html>
  );
}
